In [9]:
import pandas as pd
import numpy as np
import nltk
import csv



In [26]:
name = './sequenceData/processedDataDonaldTrump.csv'
directory ='./processedData/processedDataDonaldTrump.csv'

#name = './sequenceData/NOTrealDonaldTrump_tweetsSequence.csv'
#directory ='./processedData/processedDataNotDonaldTrump.csv'

#name = './sequenceData/Eminem_tweets.csv'
#directory = './processedData/Eminem_tweets.csv'

#name = './processedData/TestDonaldTrump_tweets.csv'
#directory = './TestDonaldTrump_tweets.csv'

#tweets_pd = pd.read_csv("./processedData/processedDataNotDonaldTrump.csv", delimiter='|',error_bad_lines=False)


tweets = []
with open(directory) as csvfile:
    spamreader = csv.reader(csvfile, delimiter='|')
    for row in spamreader:
        if row != []:
            tweets.append(row)
    csvfile.closed
    
tweets = np.array(tweets)

In [10]:
nltk.help.upenn_tagset()
d = {}
d['$'] = 46
d["''"] = 1
d['('] = 2
d[')'] = 3
d[','] = 4
d['--'] = 5
d['.'] = 6
d[':'] = 7
d['CC'] = 8
d['CD'] = 9
d['DT'] = 10
d['EX'] = 11
d['FW'] = 12
d['IN'] = 13
d['JJ'] = 14
d['JJR'] = 15
d['JJS'] = 16
d['LS'] = 17
d['MD'] = 18
d['NN'] = 19
d['NNP'] = 20
d['NNPS'] = 21
d['NNS'] = 22
d['PDT'] = 23
d['POS'] = 24
d['PRP'] = 25
d['PRP$'] = 26
d['RB'] = 27
d['RBR'] = 28
d['RBS'] = 29
d['RP'] = 30
d['SYM'] = 31
d['TO'] = 32
d['UH'] = 33
d['VB'] = 34
d['VBD'] = 35
d['VBG'] = 36
d['VBN'] = 37
d['VBP'] = 38
d['VBZ'] = 39
d['WDT'] = 40
d['WP'] = 41
d['WP$'] = 42
d['WRB'] = 43
d["``"] = 44
d["#"] = 45

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or

In [30]:
sequences = []
counter = 0
for tweet in tweets:
    counter+=1
    if counter%1000 == 0:
        print("at {} from {}".format(counter, len(tweets)-1))
    
    
    tweettext = tweet[1]

    if "great honor to welcome President Moon" in tweettext:
        
        print(counter, tweettext)

    
    tokens = nltk.word_tokenize(tweettext)
    tagged = nltk.pos_tag(tokens)
    sequence = []
    for t in tagged:
        #print(t[1])
        sequence.append(d[t[1]])

#     print(sequence)
#     for i in range(len(sequence)):
#         e = int(sequence[i])/(10**len(sequence[i]))
#         sequence[i]=e
#     print(sequence)
    
#     label = 0
#     if tweet[0]== 'realDonaldTrump':
#         label = 1

    sequences.append(sequence)
    
c = np.array(sequences)


#DF = pd.DataFrame(sequences2)
#DF.to_csv(name)

# with open(name, 'w+') as file:
#     writer = csv.writer(file, delimiter='|')
#     writer.writerows(c)

at 1000 from 33882
at 2000 from 33882
at 3000 from 33882
at 4000 from 33882
at 5000 from 33882
at 6000 from 33882
at 7000 from 33882
at 8000 from 33882
at 9000 from 33882
at 10000 from 33882
at 11000 from 33882
at 12000 from 33882
at 13000 from 33882
at 14000 from 33882
at 15000 from 33882
at 16000 from 33882
at 17000 from 33882
at 18000 from 33882
at 19000 from 33882
at 20000 from 33882
at 21000 from 33882
at 22000 from 33882
at 23000 from 33882
at 24000 from 33882
at 25000 from 33882
at 26000 from 33882
at 27000 from 33882
at 28000 from 33882
at 29000 from 33882
at 30000 from 33882
at 31000 from 33882
at 32000 from 33882
at 33000 from 33882


In [73]:
data = [['I', 'am', 'paul18', ''],['I', 'am', 'paul18'],['I', 'am', 'paul18'],['I', 'am', 'paul18'],['I', 'am', 'paul18']]
print(data)

[['I', 'am', 'paul18', ''], ['I', 'am', 'paul18'], ['I', 'am', 'paul18'], ['I', 'am', 'paul18'], ['I', 'am', 'paul18']]


In [74]:
import nltk
import numpy as np
ConvertedData = []
for tweet in data:
    t = np.where(np.array(tweet) != '')
    #get the tags
    tagged = np.array(nltk.pos_tag(tweet[:len(t[0])]))[:,1]
    #convet the tags to numbers
    tagsN = [d[tag] for tag in tagged]
    
    #put in a zeroed list
    zeroed = np.zeros(70)
    zeroed[:len(tagsN)]= tagsN
    onehotEncoded = (np.arange(47) == zeroed[...,None]-1).astype(int)
    ConvertedData.append(onehotEncoded)
    
ConvertedData = np.array(ConvertedData)
print(ConvertedData)  

['PRP' 'VBP' 'JJ']
['PRP' 'VBP' 'JJ']
['PRP' 'VBP' 'JJ']
['PRP' 'VBP' 'JJ']
['PRP' 'VBP' 'JJ']
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
